Enable to set random ranges to RandomEmojiOverlay parameters (#177)
Summary:
Note: there were pyre errors about `emoji_size` etc not having the attribute `getitem`, this is a false error since we only call `emoji_size[0]` once checking that it's a tuple so I added `pyre-ignore` to silence these (see V12 & 14 for the full errors).

- [x] I have read CONTRIBUTING.md to understand how to contribute to this repository :)

Added randomness to RandomEmojiOverlay parameters like emoji_size.
A motivation is that I wanted to randomly change the parameters on-the-fly, rather than "fixed" like current implementation.
This modified augmentation was actually used in ISC21 Descriptor Track 1st-place solution.

## Test Results

The tests are passed except the following error.

```
Traceback (most recent call last):
  File "/Users/shuhei.yokoo/Documents/AugLy/augly/tests/image_tests/transforms_unit_test.py", line 177, in test_RandomEmojiOverlay
    self.evaluate_class(
  File "/Users/shuhei.yokoo/Documents/AugLy/augly/tests/image_tests/base_unit_test.py", line 129, in evaluate_class
    are_equal_images(dst, ref), "Expected and outputted images do not match"
  File "/Users/shuhei.yokoo/Documents/AugLy/augly/tests/image_tests/base_unit_test.py", line 20, in are_equal_images
    return a.size == b.size and np.allclose(np.array(a), np.array(b))
  File "<__array_function__ internals>", line 5, in allclose
  File "/Users/shuhei.yokoo/.pyenv/versions/augly/lib/python3.8/site-packages/numpy/core/numeric.py", line 2249, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "<__array_function__ internals>", line 5, in isclose
  File "/Users/shuhei.yokoo/.pyenv/versions/augly/lib/python3.8/site-packages/numpy/core/numeric.py", line 2358, in isclose
    return within_tol(x, y, atol, rtol)
  File "/Users/shuhei.yokoo/.pyenv/versions/augly/lib/python3.8/site-packages/numpy/core/numeric.py", line 2339, in within_tol
    return less_equal(abs(x-y), atol + rtol * abs(y))
ValueError: operands could not be broadcast together with shapes (1080,1920,3) (1080,1920,4)

----------------------------------------------------------------------
Ran 71 tests in 35.609s

FAILED (errors=1, skipped=4)
sys:1: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/shuhei.yokoo/Documents/AugLy/augly/assets/tests/image/inputs/dfdc_1.jpg'>
```

It seems that expected image has alpha channel whereas output image doesn't have alpha channel.
I'm not sure why it happened. Replacing the expected image is needed?

Pull Request resolved: https://github.com/facebookresearch/AugLy/pull/177

Reviewed By: jbitton

Differential Revision: D33253286

Pulled By: zpapakipos

fbshipit-source-id: cebaf30ce0f1c4eee5562ee92ca1bf21ce6ab779