Augment audio to a video (#133)
Summary:
## Related Issue
Fixes https://github.com/facebookresearch/AugLy/issues/130

- [X] I have read CONTRIBUTING.md to understand how to contribute to this repository :)

<Please summarize what you are trying to achieve, what changes you made, and how they acheive the desired result.>

I'm trying to extract the audio to a temporary file and then apply some audio augmentation. After that I swap the current audio in the video with the augmented audio. I also gather metadata for the augmented audio and video. It either returns the output path (if it was specified) or the video path.

Only file that was changed was `/AugLy/augly/video/functional.py`. A question I have is what should be the description for the `audio_aug_function` param?

## Unit Tests
If your changes touch the `audio` module, please run all of the `audio` tests and paste the output here. Likewise for `image`, `text`, & `video`. If your changes could affect behavior in multiple modules, please run the tests for all potentially affected modules. If you are unsure of which modules might be affected by your changes, please just run all the unit tests.

### Video
```bash
python -m unittest discover -s augly/tests/video_tests/ -p "*"
```

Output of test suite for video
```
...../Users/admin/AugLy/augly/image/utils/utils.py:51: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/admin/AugLy/augly/assets/screenshot_templates/bboxes.json'>
  bbox = json.load(open(local_bbox_path, "rb"))[template_key]
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/Users/admin/AugLy/augly/video/helpers/metadata.py:357: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/admin/AugLy/augly/assets/screenshot_templates/web.png'>
  metadata[-1]["intensity"] = getattr(
ResourceWarning: Enable tracemalloc to get the object allocation traceback
./Users/admin/AugLy/augly/image/utils/utils.py:184: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A = np.matrix(matrix, dtype=np.float)
/Users/admin/AugLy/augly/image/utils/utils.py:184: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  A = np.matrix(matrix, dtype=np.float)
/Users/admin/opt/anaconda3/envs/augly/lib/python3.9/site-packages/numpy/matrixlib/defmatrix.py:69: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  return matrix(data, dtype=dtype, copy=False)
..
======================================================================
FAIL: test_ReplaceWithBackground (transforms.composite_test.TransformsVideoUnitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/admin/AugLy/augly/tests/video_tests/transforms/composite_test.py", line 75, in test_ReplaceWithBackground
    self.evaluate_class(
  File "/Users/admin/AugLy/augly/tests/video_tests/base_unit_test.py", line 122, in evaluate_class
    self.assertTrue(
AssertionError: False is not true

----------------------------------------------------------------------
Ran 63 tests in 813.840s

FAILED (failures=1)
```

## Other testing
N/A only looking for some feedback on the work I did so far

If applicable, test your changes and paste the output here. For example, if your changes affect the requirements/installation, then test installing augly in a fresh conda env, then make sure you are able to import augly & run the unit test

Pull Request resolved: https://github.com/facebookresearch/AugLy/pull/133

Reviewed By: zpapakipos

Differential Revision: D31368459

Pulled By: jbitton

fbshipit-source-id: 9c76057d1a2057ed25b317f2eb3fd1808c92bd8d